// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: change_events.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getChangeEventByID = `-- name: GetChangeEventByID :one
SELECT
  id,
  entity_type,
  entity_id,
  user_id,
  op_type,
  version,
  payload,
  created_at,
  updated_at,
  deleted_at
FROM change_events
WHERE id = $1
`

type GetChangeEventByIDRow struct {
	ID         int64
	EntityType string
	EntityID   pgtype.UUID
	UserID     pgtype.UUID
	OpType     string
	Version    int64
	Payload    []byte
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	DeletedAt  pgtype.Timestamptz
}

func (q *Queries) GetChangeEventByID(ctx context.Context, id int64) (GetChangeEventByIDRow, error) {
	row := q.db.QueryRow(ctx, getChangeEventByID, id)
	var i GetChangeEventByIDRow
	err := row.Scan(
		&i.ID,
		&i.EntityType,
		&i.EntityID,
		&i.UserID,
		&i.OpType,
		&i.Version,
		&i.Payload,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const insertChangeEvent = `-- name: InsertChangeEvent :exec
INSERT INTO change_events (
  entity_type,
  entity_id,
  user_id,
  op_type,
  version,
  payload,
  created_at,
  updated_at,
  deleted_at
) VALUES (
  $1, $2, $3, $4, $5, $6, NOW(), NOW(), NULL
)
`

type InsertChangeEventParams struct {
	EntityType string
	EntityID   pgtype.UUID
	UserID     pgtype.UUID
	OpType     string
	Version    int64
	Payload    []byte
}

func (q *Queries) InsertChangeEvent(ctx context.Context, arg InsertChangeEventParams) error {
	_, err := q.db.Exec(ctx, insertChangeEvent,
		arg.EntityType,
		arg.EntityID,
		arg.UserID,
		arg.OpType,
		arg.Version,
		arg.Payload,
	)
	return err
}

const listChangeEvents = `-- name: ListChangeEvents :many
SELECT
  id,
  entity_type,
  entity_id,
  user_id,
  op_type,
  version,
  payload,
  created_at,
  updated_at,
  deleted_at
FROM change_events
ORDER BY created_at DESC, id DESC
LIMIT $1 OFFSET $2
`

type ListChangeEventsParams struct {
	Limit  int32
	Offset int32
}

type ListChangeEventsRow struct {
	ID         int64
	EntityType string
	EntityID   pgtype.UUID
	UserID     pgtype.UUID
	OpType     string
	Version    int64
	Payload    []byte
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	DeletedAt  pgtype.Timestamptz
}

func (q *Queries) ListChangeEvents(ctx context.Context, arg ListChangeEventsParams) ([]ListChangeEventsRow, error) {
	rows, err := q.db.Query(ctx, listChangeEvents, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChangeEventsRow
	for rows.Next() {
		var i ListChangeEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.EntityType,
			&i.EntityID,
			&i.UserID,
			&i.OpType,
			&i.Version,
			&i.Payload,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
