// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Name      string
	Currency  string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
	Version   int64
}

type Category struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Name      string
	IsIncome  bool
	ParentID  pgtype.UUID
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
	Version   int64
}

type ChangeEvent struct {
	ID         int64
	EntityType string
	EntityID   pgtype.UUID
	UserID     pgtype.UUID
	OpType     string
	Payload    []byte
	Version    int64
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	DeletedAt  pgtype.Timestamptz
}

type MonthlyBalance struct {
	UserID    pgtype.UUID
	AccountID pgtype.UUID
	MonthKey  string
	Balance   pgtype.Numeric
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

type ProjectionCursor struct {
	ProjectorName string
	LastEventID   int64
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	DeletedAt     pgtype.Timestamptz
}

type RefreshToken struct {
	ID             pgtype.UUID
	UserID         pgtype.UUID
	EncryptedToken string
	ExpiresAt      pgtype.Timestamptz
	Revoked        bool
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	DeletedAt      pgtype.Timestamptz
}

type SheetMapping struct {
	ID           pgtype.UUID
	ConnectionID pgtype.UUID
	SheetColumn  string
	DbField      string
	Transform    []byte
	Version      int64
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
}

type SheetsConnection struct {
	ID           pgtype.UUID
	UserID       pgtype.UUID
	GoogleUserID string
	AccessToken  string
	RefreshToken pgtype.Text
	TokenExpiry  pgtype.Timestamptz
	SheetID      string
	SheetRange   pgtype.Text
	SyncMode     string
	LastSyncedAt pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
	Version      int64
}

type SyncQueue struct {
	ID          int64
	UserID      pgtype.UUID
	OpType      string
	Payload     []byte
	Attempts    int32
	AvailableAt pgtype.Timestamptz
	MaxAttempts int32
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
	Version     int64
}

type Transaction struct {
	ID           pgtype.UUID
	UserID       pgtype.UUID
	AccountID    pgtype.UUID
	Amount       pgtype.Numeric
	Currency     string
	Type         string
	CategoryID   pgtype.UUID
	Description  pgtype.Text
	OccurredAt   pgtype.Timestamptz
	Metadata     []byte
	Version      int64
	LastModified pgtype.Timestamptz
	Source       string
	SheetsRowID  pgtype.Text
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
}

type TransactionSummary struct {
	UserID      pgtype.UUID
	PeriodKey   string
	Currency    string
	Type        string
	TotalAmount pgtype.Numeric
	Count       int64
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
}

type User struct {
	ID             pgtype.UUID
	Email          string
	DisplayName    pgtype.Text
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	DeletedAt      pgtype.Timestamptz
	Version        int64
	HashedPassword string
}
