// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transactions.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countTransactionsByUser = `-- name: CountTransactionsByUser :one
SELECT COUNT(*)::bigint AS total
FROM transactions
WHERE user_id = $1
  AND deleted = false
`

// Count non-deleted transactions for a user.
func (q *Queries) CountTransactionsByUser(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countTransactionsByUser, userID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (
  user_id,
  account_id,
  amount,
  currency,
  type,
  category_id,
  description,
  occurred_at,
  metadata,
  version,
  last_modified,
  source,
  sheets_row_id,
  deleted
) VALUES (
  $1, $2, $3, $4, $5,
  $6, $7, $8, $9,
  $10, $11, $12, $13, $14
)
RETURNING id, user_id, account_id, amount, currency, type, category_id, description, occurred_at, metadata, version, last_modified, source, sheets_row_id, deleted
`

type CreateTransactionParams struct {
	UserID       pgtype.UUID
	AccountID    pgtype.UUID
	Amount       pgtype.Numeric
	Currency     string
	Type         string
	CategoryID   pgtype.UUID
	Description  pgtype.Text
	OccurredAt   pgtype.Timestamptz
	Metadata     []byte
	Version      int64
	LastModified pgtype.Timestamptz
	Source       string
	SheetsRowID  pgtype.Text
	Deleted      bool
}

// Create a new transaction for a user.
func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.UserID,
		arg.AccountID,
		arg.Amount,
		arg.Currency,
		arg.Type,
		arg.CategoryID,
		arg.Description,
		arg.OccurredAt,
		arg.Metadata,
		arg.Version,
		arg.LastModified,
		arg.Source,
		arg.SheetsRowID,
		arg.Deleted,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.Amount,
		&i.Currency,
		&i.Type,
		&i.CategoryID,
		&i.Description,
		&i.OccurredAt,
		&i.Metadata,
		&i.Version,
		&i.LastModified,
		&i.Source,
		&i.SheetsRowID,
		&i.Deleted,
	)
	return i, err
}

const getTransactionByID = `-- name: GetTransactionByID :one
SELECT id, user_id, account_id, amount, currency, type, category_id, description, occurred_at, metadata, version, last_modified, source, sheets_row_id, deleted
FROM transactions
WHERE id = $1
  AND user_id = $2
  AND deleted = false
`

type GetTransactionByIDParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

// Fetch a single non-deleted transaction by id and user.
func (q *Queries) GetTransactionByID(ctx context.Context, arg GetTransactionByIDParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransactionByID, arg.ID, arg.UserID)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.Amount,
		&i.Currency,
		&i.Type,
		&i.CategoryID,
		&i.Description,
		&i.OccurredAt,
		&i.Metadata,
		&i.Version,
		&i.LastModified,
		&i.Source,
		&i.SheetsRowID,
		&i.Deleted,
	)
	return i, err
}

const getTransactionByIDOnly = `-- name: GetTransactionByIDOnly :one
SELECT id, user_id, account_id, amount, currency, type, category_id, description, occurred_at, metadata, version, last_modified, source, sheets_row_id, deleted
FROM transactions
WHERE id = $1
`

// Fetch a single transaction by id (for use inside tx when user_id not needed).
func (q *Queries) GetTransactionByIDOnly(ctx context.Context, id pgtype.UUID) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransactionByIDOnly, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.Amount,
		&i.Currency,
		&i.Type,
		&i.CategoryID,
		&i.Description,
		&i.OccurredAt,
		&i.Metadata,
		&i.Version,
		&i.LastModified,
		&i.Source,
		&i.SheetsRowID,
		&i.Deleted,
	)
	return i, err
}

const listTransactionsByUser = `-- name: ListTransactionsByUser :many
SELECT id, user_id, account_id, amount, currency, type, category_id, description, occurred_at, metadata, version, last_modified, source, sheets_row_id, deleted
FROM transactions
WHERE user_id = $1
  AND deleted = false
ORDER BY occurred_at DESC
LIMIT $2 OFFSET $3
`

type ListTransactionsByUserParams struct {
	UserID pgtype.UUID
	Limit  int32
	Offset int32
}

// List all non-deleted transactions for a user with pagination.
func (q *Queries) ListTransactionsByUser(ctx context.Context, arg ListTransactionsByUserParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listTransactionsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccountID,
			&i.Amount,
			&i.Currency,
			&i.Type,
			&i.CategoryID,
			&i.Description,
			&i.OccurredAt,
			&i.Metadata,
			&i.Version,
			&i.LastModified,
			&i.Source,
			&i.SheetsRowID,
			&i.Deleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteTransaction = `-- name: SoftDeleteTransaction :one
UPDATE transactions
SET
  deleted       = true,
  last_modified = now(),
  version       = version + 1
WHERE id = $1
  AND user_id = $2
  AND deleted = false
RETURNING id, user_id, account_id, amount, currency, type, category_id, description, occurred_at, metadata, version, last_modified, source, sheets_row_id, deleted
`

type SoftDeleteTransactionParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

// Soft-delete a transaction (id + user_id).
func (q *Queries) SoftDeleteTransaction(ctx context.Context, arg SoftDeleteTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, softDeleteTransaction, arg.ID, arg.UserID)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.Amount,
		&i.Currency,
		&i.Type,
		&i.CategoryID,
		&i.Description,
		&i.OccurredAt,
		&i.Metadata,
		&i.Version,
		&i.LastModified,
		&i.Source,
		&i.SheetsRowID,
		&i.Deleted,
	)
	return i, err
}

const softDeleteTransactionByID = `-- name: SoftDeleteTransactionByID :one
UPDATE transactions
SET
  deleted       = true,
  last_modified = now(),
  version       = version + 1
WHERE id = $1
  AND deleted = false
RETURNING id, user_id, account_id, amount, currency, type, category_id, description, occurred_at, metadata, version, last_modified, source, sheets_row_id, deleted
`

// Soft-delete a transaction by id only (for use when user_id not in scope).
func (q *Queries) SoftDeleteTransactionByID(ctx context.Context, id pgtype.UUID) (Transaction, error) {
	row := q.db.QueryRow(ctx, softDeleteTransactionByID, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.Amount,
		&i.Currency,
		&i.Type,
		&i.CategoryID,
		&i.Description,
		&i.OccurredAt,
		&i.Metadata,
		&i.Version,
		&i.LastModified,
		&i.Source,
		&i.SheetsRowID,
		&i.Deleted,
	)
	return i, err
}

const updateTransaction = `-- name: UpdateTransaction :one
UPDATE transactions
SET
  account_id    = $3,
  amount        = $4,
  currency      = $5,
  type          = $6,
  category_id   = $7,
  description   = $8,
  occurred_at   = $9,
  metadata      = $10,
  last_modified = now(),
  source        = $11,
  sheets_row_id = $12,
  version       = version + 1
WHERE id = $1
  AND user_id = $2
RETURNING id, user_id, account_id, amount, currency, type, category_id, description, occurred_at, metadata, version, last_modified, source, sheets_row_id, deleted
`

type UpdateTransactionParams struct {
	ID          pgtype.UUID
	UserID      pgtype.UUID
	AccountID   pgtype.UUID
	Amount      pgtype.Numeric
	Currency    string
	Type        string
	CategoryID  pgtype.UUID
	Description pgtype.Text
	OccurredAt  pgtype.Timestamptz
	Metadata    []byte
	Source      string
	SheetsRowID pgtype.Text
}

// Update an existing transaction and bump the version.
func (q *Queries) UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, updateTransaction,
		arg.ID,
		arg.UserID,
		arg.AccountID,
		arg.Amount,
		arg.Currency,
		arg.Type,
		arg.CategoryID,
		arg.Description,
		arg.OccurredAt,
		arg.Metadata,
		arg.Source,
		arg.SheetsRowID,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.Amount,
		&i.Currency,
		&i.Type,
		&i.CategoryID,
		&i.Description,
		&i.OccurredAt,
		&i.Metadata,
		&i.Version,
		&i.LastModified,
		&i.Source,
		&i.SheetsRowID,
		&i.Deleted,
	)
	return i, err
}
