// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"moon-eye/backend/internal/db"

	"github.com/jackc/pgx/v5"
	mock "github.com/stretchr/testify/mock"
)

// NewMockChangeEventRepository creates a new instance of MockChangeEventRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChangeEventRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChangeEventRepository {
	mock := &MockChangeEventRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockChangeEventRepository is an autogenerated mock type for the ChangeEventRepository type
type MockChangeEventRepository struct {
	mock.Mock
}

type MockChangeEventRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChangeEventRepository) EXPECT() *MockChangeEventRepository_Expecter {
	return &MockChangeEventRepository_Expecter{mock: &_m.Mock}
}

// Insert provides a mock function for the type MockChangeEventRepository
func (_mock *MockChangeEventRepository) Insert(ctx context.Context, tx pgx.Tx, e db.ChangeEvent) error {
	ret := _mock.Called(ctx, tx, e)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, pgx.Tx, db.ChangeEvent) error); ok {
		r0 = returnFunc(ctx, tx, e)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockChangeEventRepository_Insert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Insert'
type MockChangeEventRepository_Insert_Call struct {
	*mock.Call
}

// Insert is a helper method to define mock.On call
//   - ctx context.Context
//   - tx pgx.Tx
//   - e db.ChangeEvent
func (_e *MockChangeEventRepository_Expecter) Insert(ctx interface{}, tx interface{}, e interface{}) *MockChangeEventRepository_Insert_Call {
	return &MockChangeEventRepository_Insert_Call{Call: _e.mock.On("Insert", ctx, tx, e)}
}

func (_c *MockChangeEventRepository_Insert_Call) Run(run func(ctx context.Context, tx pgx.Tx, e db.ChangeEvent)) *MockChangeEventRepository_Insert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 pgx.Tx
		if args[1] != nil {
			arg1 = args[1].(pgx.Tx)
		}
		var arg2 db.ChangeEvent
		if args[2] != nil {
			arg2 = args[2].(db.ChangeEvent)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockChangeEventRepository_Insert_Call) Return(err error) *MockChangeEventRepository_Insert_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockChangeEventRepository_Insert_Call) RunAndReturn(run func(ctx context.Context, tx pgx.Tx, e db.ChangeEvent) error) *MockChangeEventRepository_Insert_Call {
	_c.Call.Return(run)
	return _c
}
