// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"moon-eye/backend/internal/sync"

	mock "github.com/stretchr/testify/mock"
)

// NewMockSheetsClient creates a new instance of MockSheetsClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSheetsClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSheetsClient {
	mock := &MockSheetsClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSheetsClient is an autogenerated mock type for the SheetsClient type
type MockSheetsClient struct {
	mock.Mock
}

type MockSheetsClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSheetsClient) EXPECT() *MockSheetsClient_Expecter {
	return &MockSheetsClient_Expecter{mock: &_m.Mock}
}

// ApplyChanges provides a mock function for the type MockSheetsClient
func (_mock *MockSheetsClient) ApplyChanges(ctx context.Context, conn syncworker.SheetsConnection, rows []syncworker.SheetRowChange) error {
	ret := _mock.Called(ctx, conn, rows)

	if len(ret) == 0 {
		panic("no return value specified for ApplyChanges")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, syncworker.SheetsConnection, []syncworker.SheetRowChange) error); ok {
		r0 = returnFunc(ctx, conn, rows)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSheetsClient_ApplyChanges_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ApplyChanges'
type MockSheetsClient_ApplyChanges_Call struct {
	*mock.Call
}

// ApplyChanges is a helper method to define mock.On call
//   - ctx context.Context
//   - conn syncworker.SheetsConnection
//   - rows []syncworker.SheetRowChange
func (_e *MockSheetsClient_Expecter) ApplyChanges(ctx interface{}, conn interface{}, rows interface{}) *MockSheetsClient_ApplyChanges_Call {
	return &MockSheetsClient_ApplyChanges_Call{Call: _e.mock.On("ApplyChanges", ctx, conn, rows)}
}

func (_c *MockSheetsClient_ApplyChanges_Call) Run(run func(ctx context.Context, conn syncworker.SheetsConnection, rows []syncworker.SheetRowChange)) *MockSheetsClient_ApplyChanges_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 syncworker.SheetsConnection
		if args[1] != nil {
			arg1 = args[1].(syncworker.SheetsConnection)
		}
		var arg2 []syncworker.SheetRowChange
		if args[2] != nil {
			arg2 = args[2].([]syncworker.SheetRowChange)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSheetsClient_ApplyChanges_Call) Return(err error) *MockSheetsClient_ApplyChanges_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSheetsClient_ApplyChanges_Call) RunAndReturn(run func(ctx context.Context, conn syncworker.SheetsConnection, rows []syncworker.SheetRowChange) error) *MockSheetsClient_ApplyChanges_Call {
	_c.Call.Return(run)
	return _c
}

// FetchChanges provides a mock function for the type MockSheetsClient
func (_mock *MockSheetsClient) FetchChanges(ctx context.Context, conn syncworker.SheetsConnection, cursor string) (syncworker.Changes, string, error) {
	ret := _mock.Called(ctx, conn, cursor)

	if len(ret) == 0 {
		panic("no return value specified for FetchChanges")
	}

	var r0 syncworker.Changes
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, syncworker.SheetsConnection, string) (syncworker.Changes, string, error)); ok {
		return returnFunc(ctx, conn, cursor)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, syncworker.SheetsConnection, string) syncworker.Changes); ok {
		r0 = returnFunc(ctx, conn, cursor)
	} else {
		r0 = ret.Get(0).(syncworker.Changes)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, syncworker.SheetsConnection, string) string); ok {
		r1 = returnFunc(ctx, conn, cursor)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, syncworker.SheetsConnection, string) error); ok {
		r2 = returnFunc(ctx, conn, cursor)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockSheetsClient_FetchChanges_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchChanges'
type MockSheetsClient_FetchChanges_Call struct {
	*mock.Call
}

// FetchChanges is a helper method to define mock.On call
//   - ctx context.Context
//   - conn syncworker.SheetsConnection
//   - cursor string
func (_e *MockSheetsClient_Expecter) FetchChanges(ctx interface{}, conn interface{}, cursor interface{}) *MockSheetsClient_FetchChanges_Call {
	return &MockSheetsClient_FetchChanges_Call{Call: _e.mock.On("FetchChanges", ctx, conn, cursor)}
}

func (_c *MockSheetsClient_FetchChanges_Call) Run(run func(ctx context.Context, conn syncworker.SheetsConnection, cursor string)) *MockSheetsClient_FetchChanges_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 syncworker.SheetsConnection
		if args[1] != nil {
			arg1 = args[1].(syncworker.SheetsConnection)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSheetsClient_FetchChanges_Call) Return(changes syncworker.Changes, s string, err error) *MockSheetsClient_FetchChanges_Call {
	_c.Call.Return(changes, s, err)
	return _c
}

func (_c *MockSheetsClient_FetchChanges_Call) RunAndReturn(run func(ctx context.Context, conn syncworker.SheetsConnection, cursor string) (syncworker.Changes, string, error)) *MockSheetsClient_FetchChanges_Call {
	_c.Call.Return(run)
	return _c
}
