// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"moon-eye/backend/internal/service"

	mock "github.com/stretchr/testify/mock"
)

// NewMockSyncQueue creates a new instance of MockSyncQueue. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSyncQueue(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSyncQueue {
	mock := &MockSyncQueue{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSyncQueue is an autogenerated mock type for the SyncQueue type
type MockSyncQueue struct {
	mock.Mock
}

type MockSyncQueue_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSyncQueue) EXPECT() *MockSyncQueue_Expecter {
	return &MockSyncQueue_Expecter{mock: &_m.Mock}
}

// EnqueueSyncJob provides a mock function for the type MockSyncQueue
func (_mock *MockSyncQueue) EnqueueSyncJob(ctx context.Context, job service.SyncJob) error {
	ret := _mock.Called(ctx, job)

	if len(ret) == 0 {
		panic("no return value specified for EnqueueSyncJob")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, service.SyncJob) error); ok {
		r0 = returnFunc(ctx, job)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSyncQueue_EnqueueSyncJob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnqueueSyncJob'
type MockSyncQueue_EnqueueSyncJob_Call struct {
	*mock.Call
}

// EnqueueSyncJob is a helper method to define mock.On call
//   - ctx context.Context
//   - job service.SyncJob
func (_e *MockSyncQueue_Expecter) EnqueueSyncJob(ctx interface{}, job interface{}) *MockSyncQueue_EnqueueSyncJob_Call {
	return &MockSyncQueue_EnqueueSyncJob_Call{Call: _e.mock.On("EnqueueSyncJob", ctx, job)}
}

func (_c *MockSyncQueue_EnqueueSyncJob_Call) Run(run func(ctx context.Context, job service.SyncJob)) *MockSyncQueue_EnqueueSyncJob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 service.SyncJob
		if args[1] != nil {
			arg1 = args[1].(service.SyncJob)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSyncQueue_EnqueueSyncJob_Call) Return(err error) *MockSyncQueue_EnqueueSyncJob_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSyncQueue_EnqueueSyncJob_Call) RunAndReturn(run func(ctx context.Context, job service.SyncJob) error) *MockSyncQueue_EnqueueSyncJob_Call {
	_c.Call.Return(run)
	return _c
}
