// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"moon-eye/backend/internal/db"

	"github.com/gofrs/uuid"
	"github.com/jackc/pgx/v5"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTransactionRepository creates a new instance of MockTransactionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTransactionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTransactionRepository {
	mock := &MockTransactionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTransactionRepository is an autogenerated mock type for the TransactionRepository type
type MockTransactionRepository struct {
	mock.Mock
}

type MockTransactionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTransactionRepository) EXPECT() *MockTransactionRepository_Expecter {
	return &MockTransactionRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockTransactionRepository
func (_mock *MockTransactionRepository) Create(ctx context.Context, tx pgx.Tx, params db.CreateTransactionParams) (*db.Transaction, error) {
	ret := _mock.Called(ctx, tx, params)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *db.Transaction
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, pgx.Tx, db.CreateTransactionParams) (*db.Transaction, error)); ok {
		return returnFunc(ctx, tx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, pgx.Tx, db.CreateTransactionParams) *db.Transaction); ok {
		r0 = returnFunc(ctx, tx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.Transaction)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, pgx.Tx, db.CreateTransactionParams) error); ok {
		r1 = returnFunc(ctx, tx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTransactionRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockTransactionRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - tx pgx.Tx
//   - params db.CreateTransactionParams
func (_e *MockTransactionRepository_Expecter) Create(ctx interface{}, tx interface{}, params interface{}) *MockTransactionRepository_Create_Call {
	return &MockTransactionRepository_Create_Call{Call: _e.mock.On("Create", ctx, tx, params)}
}

func (_c *MockTransactionRepository_Create_Call) Run(run func(ctx context.Context, tx pgx.Tx, params db.CreateTransactionParams)) *MockTransactionRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 pgx.Tx
		if args[1] != nil {
			arg1 = args[1].(pgx.Tx)
		}
		var arg2 db.CreateTransactionParams
		if args[2] != nil {
			arg2 = args[2].(db.CreateTransactionParams)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTransactionRepository_Create_Call) Return(transaction *db.Transaction, err error) *MockTransactionRepository_Create_Call {
	_c.Call.Return(transaction, err)
	return _c
}

func (_c *MockTransactionRepository_Create_Call) RunAndReturn(run func(ctx context.Context, tx pgx.Tx, params db.CreateTransactionParams) (*db.Transaction, error)) *MockTransactionRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockTransactionRepository
func (_mock *MockTransactionRepository) GetByID(ctx context.Context, tx pgx.Tx, id uuid.UUID) (*db.Transaction, error) {
	ret := _mock.Called(ctx, tx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *db.Transaction
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, pgx.Tx, uuid.UUID) (*db.Transaction, error)); ok {
		return returnFunc(ctx, tx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, pgx.Tx, uuid.UUID) *db.Transaction); ok {
		r0 = returnFunc(ctx, tx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.Transaction)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, pgx.Tx, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, tx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTransactionRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockTransactionRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - tx pgx.Tx
//   - id uuid.UUID
func (_e *MockTransactionRepository_Expecter) GetByID(ctx interface{}, tx interface{}, id interface{}) *MockTransactionRepository_GetByID_Call {
	return &MockTransactionRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, tx, id)}
}

func (_c *MockTransactionRepository_GetByID_Call) Run(run func(ctx context.Context, tx pgx.Tx, id uuid.UUID)) *MockTransactionRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 pgx.Tx
		if args[1] != nil {
			arg1 = args[1].(pgx.Tx)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTransactionRepository_GetByID_Call) Return(transaction *db.Transaction, err error) *MockTransactionRepository_GetByID_Call {
	_c.Call.Return(transaction, err)
	return _c
}

func (_c *MockTransactionRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, tx pgx.Tx, id uuid.UUID) (*db.Transaction, error)) *MockTransactionRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockTransactionRepository
func (_mock *MockTransactionRepository) List(ctx context.Context, tx pgx.Tx, filter db.TransactionFilter) ([]db.Transaction, error) {
	ret := _mock.Called(ctx, tx, filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []db.Transaction
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, pgx.Tx, db.TransactionFilter) ([]db.Transaction, error)); ok {
		return returnFunc(ctx, tx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, pgx.Tx, db.TransactionFilter) []db.Transaction); ok {
		r0 = returnFunc(ctx, tx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.Transaction)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, pgx.Tx, db.TransactionFilter) error); ok {
		r1 = returnFunc(ctx, tx, filter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTransactionRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockTransactionRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - tx pgx.Tx
//   - filter db.TransactionFilter
func (_e *MockTransactionRepository_Expecter) List(ctx interface{}, tx interface{}, filter interface{}) *MockTransactionRepository_List_Call {
	return &MockTransactionRepository_List_Call{Call: _e.mock.On("List", ctx, tx, filter)}
}

func (_c *MockTransactionRepository_List_Call) Run(run func(ctx context.Context, tx pgx.Tx, filter db.TransactionFilter)) *MockTransactionRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 pgx.Tx
		if args[1] != nil {
			arg1 = args[1].(pgx.Tx)
		}
		var arg2 db.TransactionFilter
		if args[2] != nil {
			arg2 = args[2].(db.TransactionFilter)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTransactionRepository_List_Call) Return(transactions []db.Transaction, err error) *MockTransactionRepository_List_Call {
	_c.Call.Return(transactions, err)
	return _c
}

func (_c *MockTransactionRepository_List_Call) RunAndReturn(run func(ctx context.Context, tx pgx.Tx, filter db.TransactionFilter) ([]db.Transaction, error)) *MockTransactionRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// SoftDelete provides a mock function for the type MockTransactionRepository
func (_mock *MockTransactionRepository) SoftDelete(ctx context.Context, tx pgx.Tx, id uuid.UUID) (*db.Transaction, error) {
	ret := _mock.Called(ctx, tx, id)

	if len(ret) == 0 {
		panic("no return value specified for SoftDelete")
	}

	var r0 *db.Transaction
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, pgx.Tx, uuid.UUID) (*db.Transaction, error)); ok {
		return returnFunc(ctx, tx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, pgx.Tx, uuid.UUID) *db.Transaction); ok {
		r0 = returnFunc(ctx, tx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.Transaction)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, pgx.Tx, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, tx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTransactionRepository_SoftDelete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SoftDelete'
type MockTransactionRepository_SoftDelete_Call struct {
	*mock.Call
}

// SoftDelete is a helper method to define mock.On call
//   - ctx context.Context
//   - tx pgx.Tx
//   - id uuid.UUID
func (_e *MockTransactionRepository_Expecter) SoftDelete(ctx interface{}, tx interface{}, id interface{}) *MockTransactionRepository_SoftDelete_Call {
	return &MockTransactionRepository_SoftDelete_Call{Call: _e.mock.On("SoftDelete", ctx, tx, id)}
}

func (_c *MockTransactionRepository_SoftDelete_Call) Run(run func(ctx context.Context, tx pgx.Tx, id uuid.UUID)) *MockTransactionRepository_SoftDelete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 pgx.Tx
		if args[1] != nil {
			arg1 = args[1].(pgx.Tx)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTransactionRepository_SoftDelete_Call) Return(transaction *db.Transaction, err error) *MockTransactionRepository_SoftDelete_Call {
	_c.Call.Return(transaction, err)
	return _c
}

func (_c *MockTransactionRepository_SoftDelete_Call) RunAndReturn(run func(ctx context.Context, tx pgx.Tx, id uuid.UUID) (*db.Transaction, error)) *MockTransactionRepository_SoftDelete_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockTransactionRepository
func (_mock *MockTransactionRepository) Update(ctx context.Context, tx pgx.Tx, params db.UpdateTransactionParams) (*db.Transaction, error) {
	ret := _mock.Called(ctx, tx, params)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *db.Transaction
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, pgx.Tx, db.UpdateTransactionParams) (*db.Transaction, error)); ok {
		return returnFunc(ctx, tx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, pgx.Tx, db.UpdateTransactionParams) *db.Transaction); ok {
		r0 = returnFunc(ctx, tx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.Transaction)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, pgx.Tx, db.UpdateTransactionParams) error); ok {
		r1 = returnFunc(ctx, tx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTransactionRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockTransactionRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - tx pgx.Tx
//   - params db.UpdateTransactionParams
func (_e *MockTransactionRepository_Expecter) Update(ctx interface{}, tx interface{}, params interface{}) *MockTransactionRepository_Update_Call {
	return &MockTransactionRepository_Update_Call{Call: _e.mock.On("Update", ctx, tx, params)}
}

func (_c *MockTransactionRepository_Update_Call) Run(run func(ctx context.Context, tx pgx.Tx, params db.UpdateTransactionParams)) *MockTransactionRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 pgx.Tx
		if args[1] != nil {
			arg1 = args[1].(pgx.Tx)
		}
		var arg2 db.UpdateTransactionParams
		if args[2] != nil {
			arg2 = args[2].(db.UpdateTransactionParams)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTransactionRepository_Update_Call) Return(transaction *db.Transaction, err error) *MockTransactionRepository_Update_Call {
	_c.Call.Return(transaction, err)
	return _c
}

func (_c *MockTransactionRepository_Update_Call) RunAndReturn(run func(ctx context.Context, tx pgx.Tx, params db.UpdateTransactionParams) (*db.Transaction, error)) *MockTransactionRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
